In [3]:
#question1
import pandas as pd
df = pd.DataFrame({
    "Tid" : [1,2,3,4,5,6,7,8,9,10],
    "REFUND" : ["Yes", "No", "No", "Yes", "No", "No", "Yes" , "No", "No", "No"],
    "Marital Status" : ["Single", "Married", "Single", "Married", "Divorced", "Married", "Divorced", "Single", "Married", "Single"],
    "Cheat" : ["No", "No", "No", "No", "Yes", "No", "No" , "Yes", "No", "Yes"]
})
df

   Tid REFUND Marital Status Cheat
0    1    Yes         Single    No
1    2     No        Married    No
2    3     No         Single    No
3    4    Yes        Married    No
4    5     No       Divorced   Yes
5    6     No        Married    No
6    7    Yes       Divorced    No
7    8     No         Single   Yes
8    9     No        Married    No
9   10     No         Single   Yes

In [9]:
#ques2
df.loc[0]
df.loc[4]
df.loc[7]
df.loc[8]

Tid                     9
REFUND                 No
Marital Status    Married
Cheat                  No
Name: 8, dtype: object

In [14]:
#ques3
df.loc[3:7]
pd.concat([df.loc[4:8],df.loc[2:4]])
df.iloc[:,1:4]

  REFUND Marital Status Cheat
0    Yes         Single    No
1     No        Married    No
2     No         Single    No
3    Yes        Married    No
4     No       Divorced   Yes
5     No        Married    No
6    Yes       Divorced    No
7     No         Single   Yes
8     No        Married    No
9     No         Single   Yes

In [34]:
#ques4
import pandas as pd
d = pd.read_csv('Iris.csv')
print(d.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [39]:
#ques5
d.drop(index=3)
d.drop(columns=['SepalWidthCm'])

      Id  SepalLengthCm  PetalLengthCm  PetalWidthCm         Species
0      1            5.1            1.4           0.2     Iris-setosa
1      2            4.9            1.4           0.2     Iris-setosa
2      3            4.7            1.3           0.2     Iris-setosa
3      4            4.6            1.5           0.2     Iris-setosa
4      5            5.0            1.4           0.2     Iris-setosa
..   ...            ...            ...           ...             ...
145  146            6.7            5.2           2.3  Iris-virginica
146  147            6.3            5.0           1.9  Iris-virginica
147  148            6.5            5.2           2.0  Iris-virginica
148  149            6.2            5.4           2.3  Iris-virginica
149  150            5.9            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [61]:
#ques6
import pandas as pd
employees = {
    "Employee_ID" : [101,102,103,104,105],
    "Name" : ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department" : ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age" : [29,34,41,28,38],
    "Salary" : [50000,70000,65000,55000,60000],
    "Years_of_Experience" : [4,8,10,3,12],
    "Joining_Date" : ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender" : ["Female", "Male", "Male", "Female", "Male"],
    "Bonus" : [5000,7000,6000,4500,5000],
    "Rating" : [4.5,4,3.8,4.7,3.5]
}
df = pd.DataFrame(employees)
df.to_csv('employees.csv', index=False)
df.shape
df.info()
df.describe()
df.head()
df.tail(3)
average_salary = df['Salary'].mean()
print("Average Salary:", average_salary)
total_bonus = df['Bonus'].sum()
print("Total Bonus:", total_bonus)
youngest_age = df['Age'].min()
print("Youngest Employee Age:", youngest_age)
highest_rating = df['Rating'].max()
print("Highest Employee Rating:", highest_rating)
sorted = df.sort_values(by='Salary', ascending=False)
print(sorted)

def categorize_rating(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >= 4.0:
        return 'Good'
    else:
        return 'Average'

df['Rating_Category'] = df['Rating'].apply(categorize_rating)
print(df)

df.isnull()

df.rename(columns={"Employee_ID" : "ID"}, inplace = True)
print(df)

experienced_employee = df[df["Years_of_Experience"] > 5]
it_employee = df[df["Department"] == "IT"]
print(experienced_employee)
print(it_employee)

df["Tax"] = df["Salary"]*0.10
print(df)

df.to_csv("modified_employee.csv", index = False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes
Average Salary: 60000.0
Total Bonus: 27500
Youngest Employee Age: 28
Highest Employee Rating: 4.7
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Rating_Category
0   2020-03-15  Female   5000     4.5       Excellent
1   2017-07-19    Male   7000     4.0            Good
2   2013-06-01    Male   6000     3.8         Average
3   2021-02-10  Female   4500     4.7       Excellent
4   2010-11-25    Male   5000     3.5         Average
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Rating_Category
0  Female   5000     4.5       Excellent
1    Male   7000     4.0            Good
2    Male   6000     3.8         Average
3  Female   4500     4.7       Excellent
4    Male   5000     3.5         Average
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Rating_Category
1   Male   7000     4.0            Good
2   Male   6000     3.8         Average
4   Male   5000     3.5         Average
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Rating_Category
1   Male   7000     4.0            Good
2   Male   6000     3.8         Average
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Rating_Category     Tax
0  Female   5000     4.5       Excellent  5000.0
1    Male   7000     4.0            Good  7000.0
2    Male   6000     3.8         Average  6500.0
3  Female   4500     4.7       Excellent  5500.0
4    Male   5000     3.5         Average  6000.0